global:
  scrape_interval: 15s
  scrape_timeout: 10s
  evaluation_interval: 30s
scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
  - job_name: 'node_exporter'
    static_configs:
      - targets: [{{ groups['db_data']|first }}:9100]
  - job_name: 'postgres_exporter'
    static_configs:
      - targets: [{{ groups['db_data']|first }}:9187]
