---
- name: create exporters configuration directory
  file:
    path: /etc/exporters
    state: directory

- name: create docker-compose config
  template:
    src: docker-compose.yml
    dest: /etc/exporters/docker-compose.yml
    mode: 0644
  notify: reload exporters

- name: create systemd service unit
  template:
    src: exporters.service
    dest: /etc/systemd/system/exporters.service
  notify: restart exporters