{
 "title": "PostgreSQL",
 "time": { "from": "now-12h", "to": "now" },
 "templating": {
  "list": [
   { "name": "host", "query": "label_values(pg_up, instance)" },
   {
    "name": "work_mem",
    "query": "query_result(pg_settings_work_mem_bytes{instance=~\"$host.*\", job=~\"postgresql.*\"})"
   },
   {
    "name": "max_connections",
    "query": "query_result(pg_settings_max_connections{instance=~\"$host.*\",job=~\"postgresql.*\"})"
   },
   {
    "name": "shared_buffers",
    "query": "query_result(pg_settings_shared_buffers_bytes{instance=~\"$host.*\",job=~\"postgresql.*\"})"
   },
   {
    "name": "wal_buffers",
    "query": "query_result(pg_settings_wal_buffers_bytes{instance=~\"$host.*\",job=~\"postgresql.*\"})"
   },
   {
    "name": "wal_segment_size",
    "query": "query_result(pg_settings_wal_segment_size_bytes{instance=~\"$host.*\",job=~\"postgresql.*\"})"
   },
   {
    "name": "maintenance_work_mem",
    "query": "query_result(pg_settings_maintenance_work_mem_bytes{instance=~\"$host.*\",job=~\"postgresql.*\"})"
   },
   {
    "name": "block_size",
    "query": "query_result(pg_settings_block_size{instance=~\"$host.*\",job=~\"postgresql.*\"})"
   },
   {
    "name": "checkpoint_segments",
    "query": "query_result(pg_settings_checkpoint_segments{instance=~\"$host.*\",job=~\"postgresql.*\"})"
   },
   {
    "name": "checkpoint_timeout",
    "query": "query_result(pg_settings_checkpoint_timeout_seconds{instance=~\"$host.*\",job=~\"postgresql.*\"})"
   },
   {
    "name": "default_statistics_target",
    "query": "query_result(pg_settings_default_statistics_target{instance=~\"$host.*\",job=~\"postgresql.*\"})"
   },
   {
    "name": "seq_page_cost",
    "query": "query_result(pg_settings_seq_page_cost{instance=~\"$host.*\",job=~\"postgresql.*\"})"
   },
   {
    "name": "random_page_cost",
    "query": "query_result(pg_settings_random_page_cost{instance=~\"$host.*\",job=~\"postgresql.*\"})"
   },
   {
    "name": "effective_cache_size",
    "query": "query_result(pg_settings_effective_cache_size_bytes{instance=~\"$host.*\",job=~\"postgresql.*\"})"
   },
   {
    "name": "effective_io_concurrency",
    "query": "query_result(pg_settings_effective_io_concurrency{instance=~\"$host.*\",job=~\"postgresql.*\"})"
   },
   {
    "name": "fsync",
    "query": "query_result(pg_settings_fsync{instance=~\"$host.*\",job=~\"postgresql.*\"})"
   },
   {
    "name": "autovacuum",
    "query": "query_result(pg_settings_autovacuum{instance=~\"$host.*\",job=~\"postgresql.*\"})"
   },
   {
    "name": "autovacuum",
    "query": "query_result(pg_settings_autovacuum{instance=~\"$host.*\",job=~\"postgresql.*\"})"
   },
   {
    "name": "autovacuum_analyze_scale_factor",
    "query": "query_result(pg_settings_autovacuum_analyze_scale_factor{instance=~\"$host.*\",job=~\"postgresql.*\"})"
   },
   {
    "name": "autovacuum_analyze_threshold",
    "query": "query_result(pg_settings_autovacuum_analyze_threshold{instance=~\"$host.*\",job=~\"postgresql.*\"})"
   },
   {
    "name": "autovacuum_vacuum_cost_limit",
    "query": "query_result(pg_settings_autovacuum_vacuum_cost_limit{instance=~\"$host.*\",job=~\"postgresql.*\"})"
   },
   {
    "name": "autovacuum_vacuum_cost_delay",
    "query": "query_result(pg_settings_autovacuum_vacuum_cost_delay_seconds{instance=~\"$host.*\",job=~\"postgresql.*\"})"
   },
   {
    "name": "autovacuum_max_workers",
    "query": "query_result(pg_settings_autovacuum_max_workers{instance=~\"$host.*\",job=~\"postgresql.*\"})"
   },
   {
    "name": "autovacuum_naptime",
    "query": "query_result(pg_settings_autovacuum_naptime_seconds{instance=~\"$host.*\",job=~\"postgresql.*\"})"
   },
   {
    "name": "autovacuum_freeze_max_age",
    "query": "query_result(pg_settings_autovacuum_freeze_max_age{instance=~\"$host.*\",job=~\"postgresql.*\"})"
   },
   {
    "name": "logging_collector",
    "query": "query_result(pg_settings_logging_collector{instance=~\"$host.*\",job=~\"postgresql.*\"})"
   },
   {
    "name": "log_min_duration_statement",
    "query": "query_result(pg_settings_log_min_duration_statement_seconds{instance=~\"$host.*\",job=~\"postgresql.*\"})"
   },
   {
    "name": "log_duration",
    "query": "query_result(pg_settings_log_duration{instance=~\"$host.*\",job=~\"postgresql.*\"})"
   },
   {
    "name": "log_lock_waits",
    "query": "query_result(pg_settings_log_lock_waits{instance=~\"$host.*\",job=~\"postgresql.*\"})"
   },
   {
    "name": "max_wal_senders",
    "query": "query_result(pg_settings_max_wal_senders{instance=~\"$host.*\",job=~\"postgresql.*\"})"
   },
   {
    "name": "max_wal_size",
    "query": "query_result(pg_settings_max_wal_size_bytes{instance=~\"$host.*\",job=~\"postgresql.*\"})"
   },
   {
    "name": "wal_compression",
    "query": "query_result(pg_settings_wal_compression{instance=~\"$host.*\",job=~\"postgresql.*\"})"
   },
   {
    "name": "max_worker_processes",
    "query": "query_result(pg_settings_max_worker_processes{instance=~\"$host.*\",job=~\"postgresql.*\"})"
   },
   {
    "name": "max_parallel_workers_per_gather"
   },
   {
    "name": "max_parallel_workers",
    "query": "query_result(pg_settings_max_parallel_workers_per_gather{instance=~\"$host.*\",job=~\"postgresql.*\"})"
   },
   {
    "name": "autovacuum_work_mem",
    "query": "query_result(pg_settings_autovacuum_work_mem_bytes{instance=~\"$host.*\",job=~\"postgresql.*\"})"
   },
   {
    "name": "autovacuum_multixact_freeze_max_age",
    "query": "query_result(pg_settings_autovacuum_multixact_freeze_max_age{instance=~\"$host.*\",job=~\"postgresql.*\"})"
   },
   {
    "name": "autovacuum_vacuum_scale_factor",
    "query": "query_result(pg_settings_autovacuum_vacuum_scale_factor{instance=~\"$host.*\",job=~\"postgresql.*\"})"
   },
   {
    "name": "min_wal_size",
    "query": "query_result(pg_settings_min_wal_size_bytes{instance=~\"$host.*\",job=~\"postgresql.*\"})"
   },
   {
    "name": "autovacuum_vacuum_threshold",
    "query": "query_result(pg_settings_autovacuum_vacuum_threshold{instance=~\"$host.*\",job=~\"postgresql.*\"})"
   },
   {
    "name": "interval",
    "label": "interval",
    "query": "30s,1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   {
    "name": "device",
    "label": "device",
    "query": "label_values(node_disk_reads_completed{instance=~\"$host.*\", device!~\"dm-.+\"}, device)"
   }
  ]
 },
 "panels": [
  { "title": "Instance info", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Virtual CPUs",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "(count(node_cpu{instance=~\"$host\",mode=~\"user\"}) or (1-absent(node_cpu{instance=~\"$host\",mode=~\"user\"}))) + sum(rdsosmetrics_General_numVCPUs{instance=~\"$host\"} or up * 0)"
    }
   ]
  },
  {
   "title": "RAM",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 2, "y": 1 },
   "format": "decbytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "node_memory_MemTotal{instance=~\"$host.*\"}"
    }
   ]
  },
  {
   "title": "Virtual Memory",
   "type": "singlestat",
   "description": "RAM + SWAP",
   "gridPos": { "h": 2, "w": 3, "x": 5, "y": 1 },
   "format": "decbytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "node_memory_MemTotal{instance=~\"$host.*\"}+node_memory_SwapTotal{instance=~\"$host.*\"}"
    }
   ]
  },
  {
   "title": "Disk Space",
   "type": "singlestat",
   "description": "Sum of disk space on all partitions. Note  it can be significantly over-reported in some installations",
   "gridPos": { "h": 2, "w": 3, "x": 8, "y": 1 },
   "format": "decbytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(avg(node_filesystem_size{instance=~\"$host.*\",fstype=~\"(ext.|xfs|vfat)\"}) without (mountpoint)) without (device,fstype)"
    }
   ]
  },
  {
   "title": "Version",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 11, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "pg_settings_server_version_num{instance=~\"$host.*\"}"
    }
   ]
  },
  {
   "title": "Inactive slots",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 13, "y": 1 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "pg_slots_status_status{instance=~\"$host.*\"}"
    }
   ]
  },
  { "title": "Common", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 } },
  {
   "title": "Transactions per second (TPS), all databases",
   "type": "graph",
   "description": "commit+rollback per instance",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 4 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(pg_stat_database_xact_commit[$interval])+rate(pg_stat_database_xact_rollback[$interval])) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Autovacuum",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 },
   "collapsed": true,
   "panels": [
    {
     "title": "autovacuum per $interval (top 10)",
     "type": "graph",
     "gridPos": { "h": 5, "w": 9, "x": 0, "y": 16 },
     "yaxes": [
      { "format": "short", "label": "autovacuums" }
     ],
     "targets": [
      {
       "expr": "topk(10, increase(pg_stat_user_tables_autovacuum_count{instance=~\"$host.*\"}[$interval]))",
       "legendFormat": "autovacuum of {{ relname }}"
      }
     ]
    },
    {
     "title": "Autovacuum workers",
     "type": "graph",
     "gridPos": { "h": 6, "w": 7, "x": 9, "y": 16 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "pg_autovacuum_count_av_workers{instance=~\"$host.*\"}",
       "legendFormat": "autovacuum"
      },
      {
       "expr": "pg_autovacuum_count_av_wrap{instance=~\"$host.*\"}",
       "legendFormat": "wraparound"
      },
      {
       "expr": "pg_autovacuum_count_v_manual{instance=~\"$host.*\"}",
       "legendFormat": "manual"
      },
      {
       "expr": "pg_settings_autovacuum_max_workers{instance=~\"$host.*\"}",
       "legendFormat": "autovacuum_max_workers"
      }
     ]
    },
    {
     "title": "Database bloat, per datname %",
     "type": "graph",
     "gridPos": { "h": 6, "w": 6, "x": 16, "y": 16 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "(sum(pg_tables_bloat_bytes) by (datname) + sum(pg_indexes_bloat_bytes) by (datname)) / sum(pg_database_size) by (datname)",
       "legendFormat": "{{datname}}"
      }
     ]
    },
    {
     "title": "Max freeze age",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 21 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "pg_database_age_age{instance=~\"$host.*\"}",
       "legendFormat": "{{datname}}"
      },
      {
       "expr": "pg_settings_autovacuum_freeze_max_age{instance=~\"$host.*\"}",
       "legendFormat": "freeze_max_age"
      }
     ]
    }
   ]
  },
  {
   "title": "Background writer and checkpoints",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 },
   "collapsed": true,
   "panels": [
    {
     "title": "Buffers written ($host)",
     "type": "graph",
     "gridPos": { "h": 7, "w": 11, "x": 0, "y": 17 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "increase(pg_stat_bgwriter_buffers_checkpoint{instance=~\"$host.*\"}[$interval])*8192",
       "legendFormat": "buffers_checkpoint"
      },
      {
       "expr": "increase(pg_stat_bgwriter_buffers_backend{instance=~\"$host.*\"}[$interval])*8192",
       "legendFormat": "buffers_backend"
      },
      {
       "expr": "increase(pg_stat_bgwriter_buffers_clean{instance=~\"$host.*\"}[$interval])*8192",
       "legendFormat": "buffers_clean"
      }
     ]
    },
    {
     "title": "Checkpoints per hour",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 11, "y": 17 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "increase(pg_stat_bgwriter_checkpoints_timed{instance=~\"$host.*\"}[1h])",
       "legendFormat": "checkpoints_timed"
      },
      {
       "expr": "increase(pg_stat_bgwriter_checkpoints_req{instance=~\"$host.*\"}[1h])",
       "legendFormat": "checkpoints_wal"
      }
     ]
    }
   ]
  },
  {
   "title": "Buffers usage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 },
   "collapsed": true,
   "panels": [
    {
     "title": "Top Dirtied blocks queries",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 18 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "topk(3, rate(pg_stat_statements_shared_blks_dirtied{instance=~\"$host.*\"}[$interval]))*8192 > 1000",
       "legendFormat": "[{{ queryid }}] {{short_query}}"
      },
      {
       "expr": "(sum(rate(pg_stat_statements_shared_blks_dirtied{instance=~\"$host.*\"}[$interval])) - sum(topk(3, rate(pg_stat_statements_shared_blks_dirtied{instance=~\"$host.*\"}[$interval]))))*8192 > 1000",
       "legendFormat": "~other"
      }
     ]
    },
    {
     "title": "Top read blocks queries",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 18 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "topk(3, rate(pg_stat_statements_shared_blks_read{instance=~\"$host.*\"}[$interval]))*8192 > 1000",
       "legendFormat": "[{{ queryid }}] {{short_query}}"
      },
      {
       "expr": "(sum(rate(pg_stat_statements_shared_blks_read{instance=~\"$host.*\"}[$interval])) - sum(topk(3, rate(pg_stat_statements_shared_blks_read{instance=~\"$host.*\"}[$interval]))))*8192 > 1000",
       "legendFormat": "~other"
      }
     ]
    },
    {
     "title": "Top written blocks queries",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 18 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "topk(3, rate(pg_stat_statements_shared_blks_written{instance=~\"$host.*\"}[$interval]))*8192",
       "legendFormat": "[{{ queryid }}] {{short_query}}"
      }
     ]
    },
    {
     "title": "Top Hit blocks queries",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 24 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "topk(3, rate(pg_stat_statements_shared_blks_hit{instance=~\"$host.*\"}[$interval]))*8192",
       "legendFormat": "[{{ queryid }}] {{short_query}}"
      },
      {
       "expr": "(sum(rate(pg_stat_statements_shared_blks_hit{instance=~\"$host.*\"}[$interval])) - sum(topk(3, rate(pg_stat_statements_shared_blks_hit{instance=~\"$host.*\"}[$interval]))))*8192",
       "legendFormat": "~other"
      }
     ]
    },
    {
     "title": "Top Dirtied local blocks queries",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 24 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "topk(3, rate(pg_stat_statements_local_blks_dirtied{instance=~\"$host.*\"}[$interval]))*8192",
       "legendFormat": "[{{ queryid }}] {{short_query}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Client connections",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 },
   "collapsed": true,
   "panels": [
    {
     "title": "Connections utilization, %",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 19 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "sum(pg_stat_activity_count{instance=~\"$host.*\"}) / sum(pg_settings_max_connections{instance=~\"$host.*\"})",
       "legendFormat": "connections"
      }
     ]
    }
   ]
  },
  {
   "title": "Disk performance",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 },
   "collapsed": true,
   "panels": [
    {
     "title": "Disk IO Utilization",
     "type": "graph",
     "description": "Shows disk Utilization as percent of the time when there was at least one IO request in flight. It is designed to match utilization available in iostat tool. It is not very good measure of true IO Capacity Utilization. Consider looking at IO latency and Disk Load Graphs instead.",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 20 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "rate(node_disk_io_time_ms{device=~\"$device\", instance=~\"$host.*\"}[$interval])/1000 or \nirate(node_disk_io_time_ms{device=~\"$device\", instance=~\"$host.*\"}[5m])/1000",
       "legendFormat": "{{device}}"
      }
     ]
    },
    {
     "title": "Disk Operations",
     "type": "graph",
     "description": "Shows amount of physical IOs (reads and writes) different devices are serving. Spikes in number of IOs served often corresponds to performance problems due to IO subsystem overload.",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 20 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "(rate(node_disk_reads_completed{device=~\"$device\", instance=~\"$host.*\"}[$interval]) or \nirate(node_disk_reads_completed{device=~\"$device\", instance=~\"$host.*\"}[5m])) or\n(max_over_time(rdsosmetrics_diskIO_readIOsPS{instance=~\"$host.*\"}[$interval]) or\nmax_over_time(rdsosmetrics_diskIO_readIOsPS{instance=~\"$host.*\"}[5m])) ",
       "legendFormat": "Read: {{ device }}"
      },
      {
       "expr": "(rate(node_disk_writes_completed{device=~\"$device\", instance=~\"$host.*\"}[$interval]) or \nirate(node_disk_writes_completed{device=~\"$device\", instance=~\"$host.*\"}[5m])) or\n(max_over_time(rdsosmetrics_diskIO_writeIOsPS{instance=~\"$host.*\"}[$interval]) or\nmax_over_time(rdsosmetrics_diskIO_writeIOsPS{instance=~\"$host.*\"}[5m])) ",
       "legendFormat": "Write: {{ device }}"
      }
     ]
    },
    {
     "title": "Disk Latency",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 20 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "(rate(node_disk_read_time_ms{device=~\"$device\", instance=~\"$host.*\"}[$interval]) / \nrate(node_disk_reads_completed{device=~\"$device\", instance=~\"$host.*\"}[$interval])) or \n(irate(node_disk_read_time_ms{device=~\"$device\", instance=~\"$host.*\"}[5m]) / \nirate(node_disk_reads_completed{device=~\"$device\", instance=~\"$host.*\"}[5m])) or\navg_over_time(aws_rds_read_latency_average{instance=~\"$host.*\"}[$interval]) or \navg_over_time(aws_rds_read_latency_average{instance=~\"$host.*\"}[5m]) or\navg_over_time(rdsosmetrics_diskIO_readLatency{instance=~\"$host.*\"}[$interval]) or \navg_over_time(rdsosmetrics_diskIO_readLatency{instance=~\"$host.*\"}[5m])",
       "legendFormat": "Read - {{ device }}"
      },
      {
       "expr": "(rate(node_disk_write_time_ms{device=~\"$device\", instance=~\"$host.*\"}[$interval]) / \nrate(node_disk_writes_completed{device=~\"$device\", instance=~\"$host.*\"}[$interval])) or \n(irate(node_disk_write_time_ms{device=~\"$device\", instance=~\"$host.*\"}[5m]) / \nirate(node_disk_writes_completed{device=~\"$device\", instance=~\"$host.*\"}[5m])) or \n(avg_over_time(aws_rds_write_latency_average{instance=~\"$host.*\"}[$interval]) or \navg_over_time(aws_rds_write_latency_average{instance=~\"$host.*\"}[5m])) or\n(avg_over_time(rdsosmetrics_diskIO_writeLatency{instance=~\"$host.*\"}[$interval]) or \navg_over_time(rdsosmetrics_diskIO_writeLatency{instance=~\"$host.*\"}[5m]))",
       "legendFormat": "Write - {{ device }}"
      }
     ]
    },
    {
     "title": "Disk IO Size",
     "type": "graph",
     "description": "Shows average size of a single disk operation.",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 26 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "rate(node_disk_sectors_read{instance=~\"$host.*\", device=~\"$device\"}[$interval]) * 512 / rate(node_disk_reads_completed{instance=~\"$host.*\", device=~\"$device\"}[$interval]) or irate(node_disk_sectors_read{instance=~\"$host.*\", device=~\"$device\"}[5m]) * 512 / irate(node_disk_reads_completed{instance=~\"$host.*\", device=~\"$device\"}[5m]) ",
       "legendFormat": "Read size: {{ device }}"
      },
      {
       "expr": "rate(node_disk_sectors_written{instance=~\"$host.*\", device=~\"$device\"}[$interval]) * 512 / rate(node_disk_writes_completed{instance=~\"$host.*\", device=~\"$device\"}[$interval]) or irate(node_disk_sectors_written{instance=~\"$host.*\", device=~\"$device\"}[5m]) * 512 / irate(node_disk_writes_completed{instance=~\"$host.*\", device=~\"$device\"}[5m]) ",
       "legendFormat": "Write size: {{ device }}"
      }
     ]
    },
    {
     "title": "Disk Bandwidth",
     "type": "graph",
     "description": "Shows volume of reads and writes the storage is handling. This can be better measure of IO capacity usage for network attached and SSD storage as it is often bandwidth limited.  Amount of data being written to the disk can be used to estimate Flash storage life time.",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 26 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "(rate(node_disk_bytes_read{device=~\"$device\", instance=~\"$host.*\"}[$interval]) or \nirate(node_disk_bytes_read{device=~\"$device\", instance=~\"$host.*\"}[5m])) or\n(rate(rdsosmetrics_diskIO_readThroughput{instance=~\"$host.*\"}[$interval]) or\nirate(rdsosmetrics_diskIO_readThroughput{instance=~\"$host.*\"}[5m]))",
       "legendFormat": "Read: {{ device }}"
      },
      {
       "expr": "rate(node_disk_bytes_written{device=~\"$device\", instance=~\"$host.*\"}[$interval]) or \nirate(node_disk_bytes_written{device=~\"$device\", instance=~\"$host.*\"}[5m]) or\n(rate(rdsosmetrics_diskIO_writeThroughput{instance=~\"$host.*\"}[$interval]) or\nirate(rdsosmetrics_diskIO_writeThroughput{instance=~\"$host.*\"}[5m]))",
       "legendFormat": "Write: {{ device }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Disk usage (temp files, WAL files)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 },
   "collapsed": true,
   "panels": [
    {
     "title": "Temp files, top 10 by instance",
     "type": "graph",
     "gridPos": { "h": 7, "w": 10, "x": 0, "y": 21 },
     "yaxes": [
      { "format": "short", "label": "files" }
     ],
     "targets": [
      {
       "expr": "topk(10, increase(pg_stat_database_temp_files[$interval]))",
       "legendFormat": "{{instance}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Queries execution",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 },
   "collapsed": true,
   "panels": [
    {
     "title": "Resource allocation by time ($host)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 22 },
     "yaxes": [
      { "format": "s", "label": "Total query time" }
     ],
     "targets": [
      {
       "expr": "sum(rate(pg_stat_statements_cpu_time_seconds{instance=~\"$host.*\"}[$interval]))",
       "legendFormat": "CPU"
      },
      {
       "expr": "sum(rate(pg_stat_statements_blk_read_time_seconds{instance=~\"$host.*\"}[$interval]))",
       "legendFormat": "IO Read"
      },
      {
       "expr": "sum(rate(pg_stat_statements_blk_write_time_seconds{instance=~\"$host.*\"}[$interval]))",
       "legendFormat": "IO Write"
      },
      {
       "expr": "sum(rate(pg_stat_statements_total_time_seconds{instance=~\"$host.*\"}[$interval]))",
       "legendFormat": "Total"
      },
      {
       "expr": "count(count(node_cpu{instance=~\"$host.*\"}) without (mode)) without (cpu)",
       "legendFormat": "CPUs"
      },
      {
       "expr": "node_load1{instance=~\"$host.*\"}",
       "legendFormat": "Load 1m"
      }
     ]
    },
    {
     "title": "Top queries by time consumed",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 22 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "topk(5, rate(pg_stat_statements_total_time_seconds{instance=~\"$host.*\"}[$interval]))",
       "legendFormat": "[{{ queryid }}] {{short_query}}"
      },
      {
       "expr": "sum(rate(pg_stat_statements_total_time_seconds{instance=~\"$host.*\"}[$interval])) - sum(topk(5, rate(pg_stat_statements_total_time_seconds{instance=~\"$host.*\"}[$interval])))",
       "legendFormat": "~other"
      }
     ]
    },
    {
     "title": "Top CPU time queries",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 30 },
     "yaxes": [
      {
       "format": "s",
       "label": "Total execution cpu_time per queryid"
      }
     ],
     "targets": [
      {
       "expr": "topk(5, rate(pg_stat_statements_cpu_time_seconds{instance=~\"$host.*\"}[$interval]))",
       "legendFormat": "[{{ queryid }}] {{short_query}}"
      },
      {
       "expr": "sum(rate(pg_stat_statements_cpu_time_seconds{instance=~\"$host.*\"}[$interval])) - sum(topk(5, rate(pg_stat_statements_cpu_time_seconds{instance=~\"$host.*\"}[$interval])))",
       "legendFormat": "~other"
      }
     ]
    },
    {
     "title": "Top IO time queries",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 30 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "topk(5, rate(pg_stat_statements_blk_read_time_seconds{instance=~\"$host.*\"}[$interval]) + rate(pg_stat_statements_blk_write_time_seconds{instance=~\"$host.*\"}[$interval]))",
       "legendFormat": "[{{ queryid }}] {{short_query}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Settings",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 },
   "collapsed": true,
   "panels": [
    {
     "title": "PostgreSQL Settings",
     "type": "text",
     "gridPos": { "h": 18, "w": 24, "x": 0, "y": 23 },
     "content": "<table style=\"width:100%; border: 2px solid grey;\">\n  <tr><td></td><td></td><td></td><td></td></tr>\n  <tr><td> The maximum number of concurrent connections </td><td>${max_connections}</td><td> <i>shared_buffers</i> - Shared memory buffers (bytes) </td><td>${shared_buffers}</td></tr>\n  <tr><td> The maximum memory to be used for query workspaces (bytes)</td><td>${work_mem}</td><td> The number of disk-page buffers in shared memory for WAL (bytes)</td><td>${wal_buffers}</td></tr>\n  <tr><td> The number of pages per write ahead log segment (bytes) </td><td>${wal_segment_size}</td><td>The maximum memory to be used for query workspaces (bytes)</td><td>${maintenance_work_mem}</td></tr>\n  <tr><td> The block size in the write ahead log </td><td>${block_size}</td><td>The maximum distance in log segments between automatic WAL checkpoints</td><td>${checkpoint_segments}</td></tr>\n  <tr><td> Time spent flushing dirty buffers during checkpoint, as fraction of checkpoint interval </td><td>${checkpoint_timeout}</td><td>The maximum number of simultaneously running WAL sender processes</td><td>${max_wal_senders}</td></tr>\n  <tr><td> The minimum size to shrink the WAL to (bytes)</td><td>${min_wal_size}</td><td>The WAL size that triggers a checkpoint (bytes)</td><td>${max_wal_size}</td></tr>\n  <tr><td> Compresses full-page writes written in WAL file </td><td>${wal_compression}</td><td>Maximum number of concurrent worker processes</td><td>${max_worker_processes}</td></tr>\n  <tr><td> The maximum number of parallel processes per executor node </td><td>${max_parallel_workers_per_gather}</td><td>The maximum number of parallel processes per executor node</td><td>${max_parallel_workers}</td></tr>\n  <tr><td> The default statistics target </td><td>${default_statistics_target}</td><td>The planner's estimate of the cost of a sequentially fetched disk page </td><td>${seq_page_cost}</td></tr>\n  <tr><td> The planner's estimate of the cost of a nonsequentially fetched disk page </td><td>${random_page_cost}</td><td>The planner's assumption about the size of the disk cache</td><td>${effective_cache_size}</td></tr>\n  <tr><td> Number of simultaneous requests that can be handled efficiently by the disk subsystem </td><td>${effective_io_concurrency}</td><td>Forces synchronization of updates to disk </td><td>${fsync}</td></tr>\n  <tr><td> Starts the autovacuum subprocess </td><td>${autovacuum}</td><td>Number of tuple inserts, updates, or deletes prior to analyze as a fraction of reltuples</td><td>${autovacuum_analyze_scale_factor}</td></tr>\n  <tr><td> Minimum number of tuple inserts, updates, or deletes prior to analyze </td><td>${autovacuum_analyze_threshold}</td><td>Number of tuple updates or deletes prior to vacuum as a fraction of reltuples</td><td>${autovacuum_vacuum_scale_factor}</td></tr>\n  <tr><td> Minimum number of tuple updates or deletes prior to vacuum </td><td>${autovacuum_vacuum_threshold}</td><td>Vacuum cost amount available before napping, for autovacuum </td><td>${autovacuum_vacuum_cost_limit}</td></tr>\n  <tr><td> Vacuum cost delay in milliseconds, for autovacuum (seconds) </td><td>${autovacuum_vacuum_cost_delay}</td><td> The maximum number of simultaneously running autovacuum worker processes </td><td>${autovacuum_max_workers}</td></tr>\n  <tr><td> Time to sleep between autovacuum runs (seconds) </td><td>${autovacuum_naptime}</td><td>Age at which to autovacuum a table to prevent transaction ID wraparound </td><td>${autovacuum_freeze_max_age}</td></tr>\n  <tr><td> The maximum memory to be used by each autovacuum worker process (bytes)</td><td>${autovacuum_work_mem}</td><td>Multixact age at which to autovacuum a table to prevent multixact wraparound</td><td>${autovacuum_multixact_freeze_max_age}</td></tr>\n  <tr><td> Start a subprocess to capture stderr output and/or csvlogs into log files </td><td>${logging_collector}</td><td>Sets the minimum execution time above which statements will be logged (seconds) </td><td>${log_min_duration_statement}</td></tr>\n  <tr><td> Logs the duration of each completed SQL statement </td><td>${log_duration}</td><td>Logs long lock waits </td><td>${log_lock_waits}</td></tr>\n  <tr><td></td><td></td><td></td><td></td></tr>\n</table>"
    }
   ]
  },
  {
   "title": "Transactions",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 },
   "collapsed": true,
   "panels": [
    {
     "title": "Duration of Transactions",
     "type": "graph",
     "gridPos": { "h": 7, "w": 10, "x": 0, "y": 24 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "max_over_time(pg_stat_activity_max_tx_duration{instance='$host'}[$interval]) or\nmax_over_time(pg_stat_activity_max_tx_duration{instance='$host'}[5m])",
       "legendFormat": "{{state}}"
      }
     ]
    },
    {
     "title": "TPS, $host",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 10, "y": 24 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum by (instance)(rate(pg_stat_database_xact_commit{instance=~\"$host.*\"}[$interval]))",
       "legendFormat": "xact"
      },
      {
       "expr": "sum by (instance)(rate(pg_stat_database_xact_rollback{instance=~\"$host.*\"}[$interval]))",
       "legendFormat": "rollback"
      },
      {
       "expr": "sum by (instance)(rate(pg_stat_database_xact_commit{instance=~\"$host.*\"}[15m]))",
       "legendFormat": "avg"
      }
     ]
    }
   ]
  }
 ]
}