{
 "title": "System Overview",
 "tags": [
  "OS",
  "Percona"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "source", "query": "prometheus" },
   { "name": "interval", "label": "Interval", "query": "1s,5s,1m,5m,1h,6h,1d" },
   {
    "name": "host",
    "label": "Host",
    "query": "label_values(node_load1, instance)"
   }
  ]
 },
 "panels": [
  {
   "title": "System Uptime",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 0 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "calculatedInterval": "10m",
     "expr": "node_time{instance=\"$host\"} - node_boot_time{instance=\"$host\"}"
    }
   ]
  },
  {
   "title": "Virtual CPUs",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "count(node_cpu{mode=\"user\", instance=\"$host\"})"
    }
   ]
  },
  {
   "title": "RAM",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 0 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "node_memory_MemTotal{instance=\"$host\"}"
    }
   ]
  },
  {
   "title": "Memory Available",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 0 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "calculatedInterval": "10m",
     "expr": "(node_memory_MemAvailable{instance=\"$host\"} or (node_memory_MemFree{instance=\"$host\"} + node_memory_Buffers{instance=\"$host\"} + node_memory_Cached{instance=\"$host\"})) / node_memory_MemTotal{instance=\"$host\"} * 100"
    }
   ]
  },
  {
   "title": "Load Average",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 4 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "calculatedInterval": "10s",
     "expr": "node_load1{instance=\"$host\"}",
     "legendFormat": "Load 1m"
    },
    {
     "expr": "node_load5{instance=\"$host\"}",
     "legendFormat": "Load 5m"
    },
    {
     "expr": "node_load15{instance=\"$host\"}",
     "legendFormat": "Load 15m"
    }
   ]
  },
  {
   "title": "Network Utilization Hourly",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 4 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "calculatedInterval": "2s",
     "expr": "sum(increase(node_network_receive_bytes{instance=\"$host\", device!=\"lo\"}[1h]))",
     "legendFormat": "Received"
    },
    {
     "calculatedInterval": "2s",
     "expr": "sum(increase(node_network_transmit_bytes{instance=\"$host\", device!=\"lo\"}[1h]))",
     "legendFormat": "Sent"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "calculatedInterval": "2s",
     "expr": "sum(rate(node_cpu{instance=\"$host\", mode!=\"idle\"}[$interval])) by (mode)* 100 / scalar(count(node_cpu{mode=\"user\", instance=\"$host\"})) or sum(irate(node_cpu{instance=\"$host\", mode!=\"idle\"}[5m])) by (mode) * 100 / scalar(count(node_cpu{mode=\"user\", instance=\"$host\"}))",
     "legendFormat": "{{ mode }}"
    }
   ]
  },
  {
   "title": "Network Traffic",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 11 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "calculatedInterval": "2s",
     "expr": "sum(rate(node_network_receive_bytes{instance=\"$host\", device!=\"lo\"}[$interval]) or irate(node_network_receive_bytes{instance=\"$host\", device!=\"lo\"}[5m]))",
     "legendFormat": "Inbound"
    },
    {
     "calculatedInterval": "2s",
     "expr": "sum(rate(node_network_transmit_bytes{instance=\"$host\", device!=\"lo\"}[$interval]) or irate(node_network_transmit_bytes{instance=\"$host\", device!=\"lo\"}[5m]))",
     "legendFormat": "Outbound"
    }
   ]
  },
  {
   "title": "Saturation Metrics",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "calculatedInterval": "2s",
     "expr": "(avg_over_time(node_procs_running{instance=\"$host\"}[$interval])-1) / scalar(count(node_cpu{mode=\"user\", instance=\"$host\"}))",
     "legendFormat": "Normalized CPU Load"
    },
    {
     "calculatedInterval": "2s",
     "expr": "avg_over_time(node_procs_blocked{instance=\"$host\"}[$interval])",
     "legendFormat": "IO Load "
    }
   ]
  },
  {
   "title": "Memory",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "calculatedInterval": "2s",
     "expr": "node_memory_MemTotal{instance=\"$host\"}",
     "legendFormat": "Total"
    },
    {
     "calculatedInterval": "2s",
     "expr": "node_memory_MemTotal{instance=\"$host\"} - (node_memory_MemAvailable{instance=\"$host\"} or (node_memory_MemFree{instance=\"$host\"} + node_memory_Buffers{instance=\"$host\"} + node_memory_Cached{instance=\"$host\"}))",
     "legendFormat": "Used"
    },
    {
     "calculatedInterval": "2s",
     "expr": "node_memory_MemAvailable{instance=\"$host\"} or (node_memory_MemFree{instance=\"$host\"} + node_memory_Buffers{instance=\"$host\"} + node_memory_Cached{instance=\"$host\"})",
     "legendFormat": "Available"
    }
   ]
  },
  {
   "title": "Memory Distribution",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 25 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "calculatedInterval": "2s",
     "expr": "node_memory_MemTotal{instance=\"$host\"} - (node_memory_MemFree{instance=\"$host\"} + node_memory_Buffers{instance=\"$host\"} + node_memory_Cached{instance=\"$host\"})",
     "legendFormat": "Used"
    },
    {
     "calculatedInterval": "2s",
     "expr": "node_memory_MemFree{instance=\"$host\"}",
     "legendFormat": "Free"
    },
    {
     "calculatedInterval": "2s",
     "expr": "node_memory_Buffers{instance=\"$host\"}",
     "legendFormat": "Buffers"
    },
    {
     "calculatedInterval": "2s",
     "expr": "node_memory_Cached{instance=\"$host\"}",
     "legendFormat": "Cached"
    }
   ]
  },
  {
   "title": "Forks",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "rate(node_forks{instance=\"$host\"}[$interval]) or irate(node_forks{instance=\"$host\"}[5m])",
     "legendFormat": "Forks"
    }
   ]
  },
  {
   "title": "Memory Advanced Details",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "calculatedInterval": "2s",
     "expr": "node_memory_Active{instance=\"$host\"}",
     "legendFormat": "Active "
    },
    {
     "calculatedInterval": "2s",
     "expr": "node_memory_Active_anon{instance=\"$host\"}",
     "legendFormat": "Active (anonymous)"
    },
    {
     "calculatedInterval": "2s",
     "expr": "node_memory_Active_file{instance=\"$host\"}",
     "legendFormat": "Active (file)"
    },
    {
     "expr": "node_memory_AnonHugePages{instance=\"$host\"}",
     "legendFormat": "Anonymous Huge Pages"
    },
    {
     "expr": "node_memory_AnonPages{instance=\"$host\"}",
     "legendFormat": "Anonymous Pages"
    },
    {
     "expr": "node_memory_Buffers{instance=\"$host\"}",
     "legendFormat": "Buffers"
    },
    {
     "expr": "node_memory_Cached{instance=\"$host\"}",
     "legendFormat": "Cached"
    },
    {
     "expr": "node_memory_DirectMap1G{instance=\"$host\"}",
     "legendFormat": "Direct Mapped 1G Pages"
    },
    {
     "expr": "node_memory_DirectMap2M{instance=\"$host\"}",
     "legendFormat": "Direct Mapped 2M Pages"
    },
    {
     "expr": "node_memory_DirectMap4k{instance=\"$host\"}",
     "legendFormat": "Direct Mapped 4k Pages"
    },
    {
     "expr": "node_memory_Inactive{instance=\"$host\"}",
     "legendFormat": "Inactive"
    },
    {
     "expr": "node_memory_Inactive_anon{instance=\"$host\"}",
     "legendFormat": "Inactive (anonymous)"
    },
    {
     "expr": "node_memory_Inactive_file{instance=\"$host\"}",
     "legendFormat": "Inactive (file)"
    },
    {
     "expr": "node_memory_KernelStack{instance=\"$host\"}",
     "legendFormat": "Kernel Stack"
    },
    {
     "expr": "node_memory_Mapped{instance=\"$host\"}",
     "legendFormat": "Memory mmap() files"
    },
    {
     "expr": "node_memory_MemAvailable{instance=\"$host\"}",
     "legendFormat": "Available Memory"
    },
    {
     "expr": "node_memory_MemFree{instance=\"$host\"}",
     "legendFormat": "Memory Free"
    },
    {
     "expr": "node_memory_MemTotal{instance=\"$host\"}",
     "legendFormat": "Total Memory"
    },
    {
     "expr": "node_memory_PageTables{instance=\"$host\"}",
     "legendFormat": "Page Tables"
    },
    {
     "expr": "node_memory_SReclaimable{instance=\"$host\"}",
     "legendFormat": "Slab Reclaimable"
    },
    {
     "expr": "node_memory_SUnreclaim{instance=\"$host\"}",
     "legendFormat": "Slab Unreclaimable"
    },
    {
     "expr": "node_memory_Shmem{instance=\"$host\"}",
     "legendFormat": "Shared Memory"
    },
    {
     "expr": "node_memory_Slab{instance=\"$host\"}",
     "legendFormat": "Slab Total"
    },
    {
     "expr": "node_memory_SwapCached{instance=\"$host\"}",
     "legendFormat": "Swap Cached"
    }
   ]
  },
  {
   "title": "Context Switches",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 33 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "rate(node_context_switches{instance=\"$host\"}[$interval]) or irate(node_context_switches{instance=\"$host\"}[5m])",
     "legendFormat": "Context Switches"
    }
   ]
  },
  {
   "title": "Swap",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 40 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "calculatedInterval": "2s",
     "expr": "node_memory_SwapTotal{instance=\"$host\"} - node_memory_SwapFree{instance=\"$host\"}",
     "legendFormat": "Used"
    },
    {
     "calculatedInterval": "2s",
     "expr": "node_memory_SwapFree{instance=\"$host\"}",
     "legendFormat": "Free"
    }
   ]
  },
  {
   "title": "Processes",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 40 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "node_procs_running{instance=\"$host\"}",
     "legendFormat": "Processes in runnable state"
    },
    {
     "calculatedInterval": "2m",
     "expr": "node_procs_blocked{instance=\"$host\"}",
     "legendFormat": "Processes blocked waiting for I/O to complete"
    }
   ]
  },
  {
   "title": "I/O Activity",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 47 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "calculatedInterval": "2s",
     "expr": "rate(node_vmstat_pgpgin{instance=\"$host\"}[$interval]) * 1024 or irate(node_vmstat_pgpgin{instance=\"$host\"}[5m]) * 1024",
     "legendFormat": "Page In"
    },
    {
     "calculatedInterval": "2s",
     "expr": "rate(node_vmstat_pgpgout{instance=\"$host\"}[$interval]) * 1024 or irate(node_vmstat_pgpgout{instance=\"$host\"}[5m]) * 1024",
     "legendFormat": "Page Out"
    }
   ]
  },
  {
   "title": "Interrupts",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 47 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "calculatedInterval": "2m",
     "expr": "rate(node_intr{instance=\"$host\"}[$interval]) or irate(node_intr{instance=\"$host\"}[5m])",
     "legendFormat": "Interrupts"
    }
   ]
  },
  {
   "title": "File Descriptors",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 54 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "calculatedInterval": "2s",
     "expr": "node_filefd_maximum{instance=\"$host\"}",
     "legendFormat": "Limit"
    },
    {
     "calculatedInterval": "2s",
     "expr": "node_filefd_allocated{instance=\"$host\"}",
     "legendFormat": "Allocated"
    }
   ]
  },
  {
   "title": "Swap Activity",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 54 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "calculatedInterval": "2s",
     "expr": "rate(node_vmstat_pswpin{instance=\"$host\"}[$interval]) * 4096 or irate(node_vmstat_pswpin{instance=\"$host\"}[5m]) * 4096",
     "legendFormat": "Swap In"
    },
    {
     "calculatedInterval": "2s",
     "expr": "rate(node_vmstat_pswpout{instance=\"$host\"}[$interval]) * 4096 or irate(node_vmstat_pswpout{instance=\"$host\"}[5m]) * 4096",
     "legendFormat": "Swap Out"
    }
   ]
  },
  {
   "title": "Free disk space",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 61 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "node_filesystem_free{instance=\"$host\"}",
     "legendFormat": "{{ device }}"
    }
   ]
  }
 ]
}